config/routes.rb
Translate::Application.routes.draw do

  

  
  
  scope "/:locale" do
   resources :profiles
   resources :translation_hints
   resources :translations_uploads
   resources :contacts
   resources :delayed_jobs
   root :to => 'help#application'
   get 'help/application', :to => 'help#application', :as => 'application_help'
   get 'help/translator', :to => 'help#translator', :as => 'translator_help'
   get 'help/translator_objects', :to => 'help#translator_objects', :as => 'translator_objects_help'
   get 'help/translation_process', :to => 'help#translation_process', :as => 'translation_process_help'
   get 'help/interpolations', :to => 'help#interpolations', :as => 'translation_interpolations_help'
   get 'help/developer', :to => 'help#developer', :as =>  'developer_help'
   get 'help/administrator', :to => 'help#administrator', :as => 'administrator_help'
   get 'help/role_of_english', :to => 'help#role_of_english', :as => 'role_of_english_help'
   get 'help/redis_databases', :to => 'help#redis_databases', :as => 'redis_databases_help' 
   get 'help/redis_instances', :to => 'help#redis_instances', :as => 'redis_instances_help'
   get 'help/getting_started', :to => 'help#getting_started', :as => 'getting_started'
   get 'help/admin_getting_started', :to => 'help#admin_getting_started', :as => 'admin_getting_started'
   get 'help/admin_users', :to => 'help#user_admin', :as => 'user_admin'
   get 'help/admin_applications_versions_languages', :to => 'help#admin_applications_versions_languages', :as => 'admin_applications_versions_languages'
   get 'help/todo', :to => 'help#todo', :as => 'todo'
   get 'help/contents', :to=> 'help#contents', :as => 'contents'
   get 'help/admin_publishing', :to=> 'help#publishing', :as => 'publishing'
   get 'help/translator_publishing', :to=> "help#translatorpublishing", :as => "translator_publishing_help"
   get 'help/administrator_publishing', :to => "help#administrator_publishing", :as => 'administrator_publishing_help'
   get 'help/admin_uploading', :to=> 'help#uploading', :as => 'uploading'
   get 'help/translator_ui', :to => 'help#translator_ui', :as => 'translator_ui'
   get 'help/developers_english', :to => 'help#developers_english', :as => 'developers_english'
   get 'help/redis_installation', :to => 'help#redis_installation', :as => 'redis_installation'
   get 'help/deep_copy', :to => 'help#deep_copy', :as => 'help_deepcopy'
   get 'help/deep_delete', :to => 'help#deep_delete', :as => 'help_deepdelete'
   get 'help/background_processes', :to => 'help#background_processes', :as => 'background_processes'
   get 'help/prerequisites', :to => 'help#prerequisites', :as => 'prerequisites'
   get 'help/workflow', :to => 'help#admin_workflow', :as => 'admin_workflow'
   get 'help/version_15', :to => "help#version_15", :as => "version_15"
   
   
=begin
   scope "/auth_user/:user_id" do
      resources :permissions
      get '/permissions_select' => 'permissions#select',      :as => :permissions_select, via: :all
      get '/set_permission/:id' => 'permissions#set_current', :as => :set_permission, via: :all
   end
   
   get '/auth_user/set_permission_by_ajax' => 'permissions#set_current_by_ajax', :as => :set_permission_by_ajax, via: :all
=end   
    
=begin
   devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}, 
     controllers: {confirmations: "users/confirmations", passwords: "users/passwords", registrations: "users/registrations", 
         sessions: "users/sessions", 
         unlocks: "users/unlocks", :invitations => 'users/invitations'}
=end
   devise_for :users, :controllers => { :invitations => 'invitations', sessions: "users/sessions" }
     match '/users/:id', :to => 'users#destroy', :as => :destroy_user, :via => :delete
     get "users/:id/edit_password",   :to => "users#edit",   :as => :edit_password
     get "users/:id/user_own_data_update", :to => "users#user_own_data_update", :as => :user_own_data_update  
     get "users/:id/user_own_data_edit", :to => "users#user_own_data_edit", :as => :user_own_data_edit
     patch "users/:id/update_password", :to => "users#update", :as => :update_password  
     patch "users/:id/unlock_user",     :to => "users#unlock_user", :as => :unlock_user
     get "users/new", :to => "users#new", :as => "new_user" 
     get "users/:id/edit", :to=> "users#edit", :as => :user_edit 
     post "users/create", :to=> "users#create", :as => :user_create
     patch "users/:id/update", :to=> "users#update", :as => :user_update
     post "users/add_invitation", :to => "users#invite_user", :as => :invite_user
     get "users/send_timezone_offset", :to => "users#timezone_offset", :as => "send_timezone_offset" 
    get "delayed_job/start", :to => "delayed_jobs#start", :as => "start_delayed_jobs_queue"
    
   resources :languages
   resources :users, :only => [:index]
   resources :whiteboard_types
   resources :whiteboards

   resources :translation_languages

    
   resources :calmapps
   resources :calmapp_versions
   post "calmapp_versions/deep_copy"=> "calmapp_versions#deep_copy", :as=>"version_deep_copy"
   get "calmapp_versions/deep_copy_params/:id"=> "calmapp_versions#deep_copy_params", :as=>"version_deep_copy_params"
   get "calmapp_versions_translation_languages/deep_copy"=> "calmapp_versions_translation_languages#deep_copy", :as=>"version_translation_language_deep_copy"
   delete "calmapp_versions_translation_languages/deep_destroy/:id" => "calmapp_versions_translation_languages#deepdestroy", :as => "versions_language_deepdestroy"
   delete "calmapp_versions/deep_destroy/:id" => "calmapp_versions#deepdestroy", :as => "version_deepdestroy"
   
   
   resources :release_statuses
   resources :redis_databases, :only=>[:index, :destroy, :edit]
   resources :redis_instances
   get 'unused_redis_database_indexes' => 'redis_instances#unused_redis_database_indexes', :as => 'redis_databases_getunused', via: :all
   get 'next_unused_redis_database_index'=> 'redis_instances#next_redis_database_index'  , :as => 'redis_databases_getnextindex', :via=> :all
   
   resources :calmapp_versions_translation_languages
   resources :translations #, :except=>:show#, :only=> [:new, :index]
   get "translations/dev_new" => "translations#dev_new", :as => "dev_new_translation", via: :all
   get "translations/dev_create" => "translations#dev_create", :as => "dev_create_translation", via: :all
   resources :translation_parameters, :only=> [ :new, :index]
   resources :special_partial_dot_keys
   

   get "redis_databases/redis_to_yaml/:id" => "redis_databases#redis_to_yaml", :as => "redis_to_yaml", via: :all
   get "calmapp_version/version_alterredisdb/:id" => "calmapp_versions#redisdbalter", :as => "version_alterredisdb"#, via: :all
   post "calmapp_version/version_publish/:id" => "redis_databases#versionpublish", :as =>"redis_databases_versionpublish" #, :via => :all
   post "calmapp_versions_translation_language/publish/:id" => "calmapp_versions_translation_languages#languagepublish", :as =>"calmapp_versions_translation_languages_languagepublish", :defaults => { :format => 'js' }
   post "calmapp_versions_translation_language/translatorproductionpublish/:id" => "calmapp_versions_translation_languages#translatorproductionpublish", :as =>"calmapp_versions_translation_languages_translatorproductionpublish", :defaults => { :format => 'js' }
   get "calmapp_versions_translation_language/translatorpublish/:id" => "calmapp_versions_translation_languages#translatorpublish", :as => "translator_publish", :defaults => { :format => 'js' }
   get "users/:id/request_translators_dbs", :to=> "users#translatorpublishing", :as => "translator_publishing"
   
   resources :translation_editor_params
   resources :special_partial_dot_keys
   resources :dot_key_code_translation_editors, :only=> [:index, :edit, :show] 
   

   get '/about',   :to => 'static_pages#about'
  end

end

app/models/calmapp.rb
# == Schema Information
# Schema version: 20110918232413
#
# Table name: calmapps
#
#  id         :integer         not null, primary key
#  name       :string(255)     not null
#  created_at :datetime
#  updated_at :datetime
#

=begin
  Every calmapp will have a number of translation files plus use common files.
  This class is the calmapp that owns translation files
  Shared (common) translation files are kept in an calmapp called Shared
=end
class Calmapp < ActiveRecord::Base
  
  attr_accessor :new_version#,  :new_redis_db#, :add_languages

  has_many :calmapp_versions, :dependent => :restrict_with_exception
  accepts_nested_attributes_for :calmapp_versions, :reject_if => :all_blank, :allow_destroy => true
  
  

  validates :name, :presence=>true, :uniqueness=>true
 
  def show_me
    return "APP " + name  + " app-id = " + id.to_s
  end
=begin  
  def save_app_version_database_languages(version=nil, redis_database=nil, languages=nil )
      Calmapp.transaction do
        save!
        if ! version.nil? then
          version.calmapp_id = id
          if languages != nil then
            version.languages=languages
          end
          the_version = calmapp_versions.create!(version.attributes)
          if the_version then
            if languages != nil then
              the_version.languages=languages
            end
            
            if ! redis_database.nil? then
              # this line sets the has_one association and saves it to the database.
              the_version.redis_database= redis_database
            end
          end
        end
      end # calmapp transaction
    return self
  end #save_app_version_database
=end
  def self.demo
    reg = Calmapp.create!( :name=>"calm_registrar")
    trans = Calmapp.create!(:name=>"translator")
  end  
  
  def can_destroy?
    return false
    #return (not new_record?) && calmapp_versions.empty?
  end
 
end

app/controllers/calmapps_controller.rb
class CalmappsController < ApplicationController
  require 'translations_helper'
  include TranslationsHelper
  before_action :authenticate_user!
  before_action :set_calmapp, only: [ :edit, :update, :destroy, :show]
  filter_access_to :all
 
  @@model ="calmapp"
  
  def index
    #@applications = Calmapp.all
    @calmapps =  Calmapp.paginate(:page => params[:page], :per_page=>15)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @calmapps }
    end
  end

  # GET /calmapps/1
  # GET /applications/1.xml
  def show

    #@calmapp = Calmapp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @calmapp }
    end
  end


  def new   
    @calmapp = Calmapp.new
    @calmapp_version = CalmappVersion.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @calmapp }
    end
  end
  def create
    @calmapp = Calmapp.new(calmapp_params) 

    respond_to do |format|
      if @calmapp.save( )
        format.html { redirect_to calmapps_path, notice: 'Calmapp was successfully created.' }
        format.json { render action: 'show', status: :created, location: @calmapp }
      else
    
        format.html { render action: 'new' }
        format.json { render json: @calmapp.errors, status: :unprocessable_entity }
      end
    end
 
  end
  # GET /calmapps/1/edit
  def edit

  end

  # PUT /applications/1
  # PUT /calmapps/1.xml
  def update
    #@calmapp = Calmapp.find(calmapp_params)#params[:id])
  
    
    respond_to do |format|
  
      if @calmapp.update(calmapp_params) #params[:calmapp], without_protection: true)
        
        tflash('update', :success, {:model=>@@model, :count=>1})
        format.html { redirect_to(calmapps_path) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @calmapp.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /calmapps/1.xml
  def destroy
    begin
      @calmapp.destroy
      tflash('delete', :success, {:model=>@@model, :count=>1})
      respond_to do |format|
        tflash('delete', :success, {:model=>@@model, :count=>1})
        format.html { redirect_to(calmapps_path) }
        format.js {}
      end 
    rescue StandardError => e
      @calmapp = nil
      flash[:error] = e.message
      respond_to do |format|
        format.js
      end
    end #rescue  
  end


  def calmapp_params
    params.require(:calmapp).permit(:name,  {calmapp_versions_attributes: [:id, :version, :_destroy]})#, :developer_ids => []})
  end
  
  def set_calmapp
    @calmapp = Calmapp.find(params[:id])
  end
  private

end

app/views/calmapps/_calmapp_versions_translation_language_fields not used.html.erb
    <li id="calmapp-versions-translation_languages" class='nested-fields' style='border:1px solid;border-color:grey; margin-left:20px;margin-right:1px margin-top:1px; margin-bottom:1px;;padding-top:2px;padding-bottom:2px;"}'>
       <%=f.inputs do%>
              <%=f.input :translation_language, :label =>false, required: false, input_html: {style: "margin-left:25%"}, as: :select, collection: TranslationLanguage.order("name ASC").all%>
              
              <span><%= link_to_remove_association t($FA +"remove_translation_language"), f, :style=>"font-size: smaller;"   %></span> 
       <%end%>
              
     </div>

app/views/calmapps/_calmapp_versions_translation_language_fields.html.erb
    <div id="calmapp-versions-translation_languages" class='nested-fields' style='border:1px solid;border-color:grey; margin-left:20px;margin-right:1px margin-top:1px; margin-bottom:1px;;padding-top:2px;padding-bottom:2px;"}'>
       <%=f.inputs do%>
              <%=f.input :translation_language, :label =>false, required: false, input_html: {style: "margin-left:25%"}, as: :select, collection: TranslationLanguage.order("name ASC").all%>
              
              <span><%= link_to_remove_association t($FA +"remove_translation_language"), f, :style=>"font-size: smaller;"   %></span> 
       <%end%>
              
     </div>

app/views/calmapps/_form.html.erb
<%= semantic_form_for(@calmapp) do |f| %>
	<%= f.inputs do %>
    <%= f.input :name %> 
           
       <p class= "nesting-heading"><%=t($ARM + "calmapp_version", :count=>3)%></p>
       <%= f.semantic_fields_for :calmapp_versions do |cav| %>         
         <%= render :partial=>'calmapp_versions/calmapp_version_simple_details', :locals=>{:f=> cav}  %>            
       <%end%> 
      <li class='nesting-add-fields'  >
        <%= link_to_add_association t($FA + 'add_calmapp_version'), f, :calmapp_versions, 
        :partial => 'calmapp_versions/calmapp_version_simple_details',
        'data-association-insertion-method' => "after" 
         %>
      </li> 
   <%end%>
   <br>
	<%= f.actions do %>
      <%= f.action :submit, :button_html => {:id=>"submit"} %>
  <% end %>
<% end %>  

app/views/calmapps/destroy.js.erb
//This will delete the line just deleted erb syntax is #{dom_id(calmapp)}
var flash_selector = "div#flash"; 
<% if not @calmapp.nil? %>
  $('#calmapp_<%=@calmapp.id %>').remove();
<%end%>
$(flash_selector).html("<%=j display_flashes%>");
timeoutID = window.setTimeout(clearFlash,30000);
function clearFlash(){
  $(flash_selector).empty();
}

app/views/calmapps/edit.html.erb
<%=theading("edit", :model=>"calmapp", :count=>1) %>
<%= render 'form' %>
<% if has_role?(:calmapps_create)%>
  <%= tlink_to('new_model', new_calmapp_path, :model=> 'calmapp', :count=>1) %> |
<%end%>
<%= tlink_to  "back", calmapps_path %>

app/views/calmapps/index.html.erb
<%=theading("listing", :model => "calmapp", :count=>10) %>
<% if Calmapp.count==0 then %>
  <%=tflash( "no_records_found", :warning)%><br/>
<%  else %>
<%= twill_paginate %>
  <table class="data">
    <tr class="dataheader">
      <th class ="dataheader"><%=tlabel('name', 'calmapp') %></th>
      <%has_role?(:calmapps_write) do%>  
        <th class="linkheader"></th>
      <% end %>
      <% if  has_role?(:calmapps_destroy)%>
        <th class="linkheader"></th>
      <% end %>
    </tr>

  <% row_class="data" %>
  <% cell_class = "data" %>
  <% link_cell_class="link"%>
  <% @calmapps.each do |calmapp| %>
    <tr class = "<%= cycle('dataeven', 'dataodd', :name => row_class) %>" id = '<%= dom_id(calmapp)%>'>
      <td class="<%= cell_class %>"><%= calmapp.name %></td>
      <%has_role?(:calmapps_write) do%>
        <%=link_edit(edit_calmapp_path(calmapp), :calmapps)%>
      <% end %>
      <% if calmapp.can_destroy?  && has_role?(:calmapps_destroy)%>
        <%=link_destroy(calmapp, :calmapp)%>
    <% end %>  
    </tr>
    <%end%>
  </table>
  <%= twill_paginate %>
  <br/>
<%end%>  
<%if has_role? :calmapps_create%>
  <%= tlink_to('new_model', new_calmapp_path, :model=> 'calmapp', :category=>:action) %>
<% end %>

app/views/calmapps/new.html.erb
<%= theading('new', :model=>'calmapp', :count=>1)%>
<%= semantic_form_for(@calmapp) do |app| %>
	 <%= render 'form' %>
<%end%>
<% if has_role?(:calmapps_create)%>
  <%= tlink_to('new_model', new_calmapp_path, :model=> 'calmapp', :count=>1)  %> |
<%end%>
<%= tlink_to("back", calmapps_path) %>