config/routes.rb
Translate::Application.routes.draw do

  

  
  
  scope "/:locale" do
   resources :profiles
   resources :translation_hints
   resources :translations_uploads
   resources :contacts
   resources :delayed_jobs
   root :to => 'help#application'
   get 'help/application', :to => 'help#application', :as => 'application_help'
   get 'help/translator', :to => 'help#translator', :as => 'translator_help'
   get 'help/translator_objects', :to => 'help#translator_objects', :as => 'translator_objects_help'
   get 'help/translation_process', :to => 'help#translation_process', :as => 'translation_process_help'
   get 'help/interpolations', :to => 'help#interpolations', :as => 'translation_interpolations_help'
   get 'help/developer', :to => 'help#developer', :as =>  'developer_help'
   get 'help/administrator', :to => 'help#administrator', :as => 'administrator_help'
   get 'help/role_of_english', :to => 'help#role_of_english', :as => 'role_of_english_help'
   get 'help/redis_databases', :to => 'help#redis_databases', :as => 'redis_databases_help' 
   get 'help/redis_instances', :to => 'help#redis_instances', :as => 'redis_instances_help'
   get 'help/getting_started', :to => 'help#getting_started', :as => 'getting_started'
   get 'help/admin_getting_started', :to => 'help#admin_getting_started', :as => 'admin_getting_started'
   get 'help/admin_users', :to => 'help#user_admin', :as => 'user_admin'
   get 'help/admin_applications_versions_languages', :to => 'help#admin_applications_versions_languages', :as => 'admin_applications_versions_languages'
   get 'help/todo', :to => 'help#todo', :as => 'todo'
   get 'help/contents', :to=> 'help#contents', :as => 'contents'
   get 'help/admin_publishing', :to=> 'help#publishing', :as => 'publishing'
   get 'help/translator_publishing', :to=> "help#translatorpublishing", :as => "translator_publishing_help"
   get 'help/administrator_publishing', :to => "help#administrator_publishing", :as => 'administrator_publishing_help'
   get 'help/admin_uploading', :to=> 'help#uploading', :as => 'uploading'
   get 'help/translator_ui', :to => 'help#translator_ui', :as => 'translator_ui'
   get 'help/developers_english', :to => 'help#developers_english', :as => 'developers_english'
   get 'help/redis_installation', :to => 'help#redis_installation', :as => 'redis_installation'
   get 'help/deep_copy', :to => 'help#deep_copy', :as => 'help_deepcopy'
   get 'help/deep_delete', :to => 'help#deep_delete', :as => 'help_deepdelete'
   get 'help/background_processes', :to => 'help#background_processes', :as => 'background_processes'
   get 'help/prerequisites', :to => 'help#prerequisites', :as => 'prerequisites'
   get 'help/workflow', :to => 'help#admin_workflow', :as => 'admin_workflow'
   get 'help/version_15', :to => "help#version_15", :as => "version_15"
   
   
=begin
   scope "/auth_user/:user_id" do
      resources :permissions
      get '/permissions_select' => 'permissions#select',      :as => :permissions_select, via: :all
      get '/set_permission/:id' => 'permissions#set_current', :as => :set_permission, via: :all
   end
   
   get '/auth_user/set_permission_by_ajax' => 'permissions#set_current_by_ajax', :as => :set_permission_by_ajax, via: :all
=end   
    
=begin
   devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}, 
     controllers: {confirmations: "users/confirmations", passwords: "users/passwords", registrations: "users/registrations", 
         sessions: "users/sessions", 
         unlocks: "users/unlocks", :invitations => 'users/invitations'}
=end
   devise_for :users, :controllers => { :invitations => 'invitations', sessions: "users/sessions" }
     match '/users/:id', :to => 'users#destroy', :as => :destroy_user, :via => :delete
     get "users/:id/edit_password",   :to => "users#edit",   :as => :edit_password
     get "users/:id/user_own_data_update", :to => "users#user_own_data_update", :as => :user_own_data_update  
     get "users/:id/user_own_data_edit", :to => "users#user_own_data_edit", :as => :user_own_data_edit
     patch "users/:id/update_password", :to => "users#update", :as => :update_password  
     patch "users/:id/unlock_user",     :to => "users#unlock_user", :as => :unlock_user
     get "users/new", :to => "users#new", :as => "new_user" 
     get "users/:id/edit", :to=> "users#edit", :as => :user_edit 
     post "users/create", :to=> "users#create", :as => :user_create
     patch "users/:id/update", :to=> "users#update", :as => :user_update
     post "users/add_invitation", :to => "users#invite_user", :as => :invite_user
     get "users/send_timezone_offset", :to => "users#timezone_offset", :as => "send_timezone_offset" 
    get "delayed_job/start", :to => "delayed_jobs#start", :as => "start_delayed_jobs_queue"
    
   resources :languages
   resources :users, :only => [:index]
   resources :whiteboard_types
   resources :whiteboards

   resources :translation_languages

    
   resources :calmapps
   resources :calmapp_versions
   post "calmapp_versions/deep_copy"=> "calmapp_versions#deep_copy", :as=>"version_deep_copy"
   get "calmapp_versions/deep_copy_params/:id"=> "calmapp_versions#deep_copy_params", :as=>"version_deep_copy_params"
   get "calmapp_versions_translation_languages/deep_copy"=> "calmapp_versions_translation_languages#deep_copy", :as=>"version_translation_language_deep_copy"
   delete "calmapp_versions_translation_languages/deep_destroy/:id" => "calmapp_versions_translation_languages#deepdestroy", :as => "versions_language_deepdestroy"
   delete "calmapp_versions/deep_destroy/:id" => "calmapp_versions#deepdestroy", :as => "version_deepdestroy"
   
   
   resources :release_statuses
   resources :redis_databases, :only=>[:index, :destroy, :edit]
   resources :redis_instances
   get 'unused_redis_database_indexes' => 'redis_instances#unused_redis_database_indexes', :as => 'redis_databases_getunused', via: :all
   get 'next_unused_redis_database_index'=> 'redis_instances#next_redis_database_index'  , :as => 'redis_databases_getnextindex', :via=> :all
   
   resources :calmapp_versions_translation_languages
   resources :translations #, :except=>:show#, :only=> [:new, :index]
   get "translations/dev_new" => "translations#dev_new", :as => "dev_new_translation", via: :all
   get "translations/dev_create" => "translations#dev_create", :as => "dev_create_translation", via: :all
   resources :translation_parameters, :only=> [ :new, :index]
   resources :special_partial_dot_keys
   

   get "redis_databases/redis_to_yaml/:id" => "redis_databases#redis_to_yaml", :as => "redis_to_yaml", via: :all
   get "calmapp_version/version_alterredisdb/:id" => "calmapp_versions#redisdbalter", :as => "version_alterredisdb"#, via: :all
   post "calmapp_version/version_publish/:id" => "redis_databases#versionpublish", :as =>"redis_databases_versionpublish" #, :via => :all
   post "calmapp_versions_translation_language/publish/:id" => "calmapp_versions_translation_languages#languagepublish", :as =>"calmapp_versions_translation_languages_languagepublish", :defaults => { :format => 'js' }
   post "calmapp_versions_translation_language/translatorproductionpublish/:id" => "calmapp_versions_translation_languages#translatorproductionpublish", :as =>"calmapp_versions_translation_languages_translatorproductionpublish", :defaults => { :format => 'js' }
   get "calmapp_versions_translation_language/translatorpublish/:id" => "calmapp_versions_translation_languages#translatorpublish", :as => "translator_publish", :defaults => { :format => 'js' }
   get "users/:id/request_translators_dbs", :to=> "users#translatorpublishing", :as => "translator_publishing"
   
   resources :translation_editor_params
   resources :special_partial_dot_keys
   resources :dot_key_code_translation_editors, :only=> [:index, :edit, :show] 
   

   get '/about',   :to => 'static_pages#about'
  end

end

app/controllers/translation_hints_controller.rb
class TranslationHintsController < ApplicationController
  respond_to :html
  before_action :authenticate_user!
  before_action :set_translation_hint, only: [:show, :edit, :update, :destroy]

  def index
     if TranslationHint.respond_to? :searchable_attr  
      searchable_attr = TranslationHint.searchable_attr 
    else 
      searchable_attr = [] 
    end

    criteria=criterion_list(searchable_attr)
    operators=operator_list( searchable_attr, criteria)

    if TranslationHint.respond_to? :sortable_attr  
      sortable_attr = TranslationHint.sortable_attr     
    else   
      sortable_attr = []   
    end

    #sorting=sort_list(sortable_attr)
    search_info = init_search(current_user, searchable_attr, sortable_attr)
    # Does the search
    activerecord_relation = TranslationHint.all
    @translation_hints = TranslationHint.search(current_user, search_info, activerecord_relation).paginate(:page => params[:page], :per_page=>15)
    #@translation_hints = TranslationHint.paginate(:page => params[:page], :per_page=>15)#TranslationHint.all
    respond_with(@translation_hints)
  end

  def show
    respond_with(@translation_hint)
  end

  def new
    @translation_hint = TranslationHint.new
    respond_with(@translation_hint)
  end

  def edit
  end

  def create
    @translation_hint = TranslationHint.new(translation_hint_params)
    @translation_hint.save
    respond_with(@translation_hints, location: translation_hints_path)
  end

  def update
    @translation_hint.update(translation_hint_params)
    #respond_with(@translation_hint, :location=> translation_hints_path)
    redirect_to(translation_hints_path)
  end

  def destroy
    begin
      @translation_hint.destroy
    rescue StandardError => e
      @calmapp_version = nil
      flash[:error] = e.message
      respond_to do |format|
        format.js
      end
    end #rescue  
  end

  private
    def set_translation_hint
      @translation_hint = TranslationHint.find(params[:id])
    end

    def translation_hint_params
      params.require(:translation_hint).permit(:heading, :example, :description, :dot_key_code)
    end
end

app/views/translation_hints/_form.html.erb
<%= semantic_form_for(@translation_hint) do |f| %>
	<%= f.inputs do %>
	         <%= f.input :dot_key_code, :required=>true  %>
				   <%= f.input :heading  %>   
				   <%= f.input :example, as: :text%>   
				   <%= f.input :description, as: :text, :required=> true  %>   
		
	<% end %>	

        <%= f.actions do %>
          <%= f.action(:submit) %>

        <% end %>
<% end %>

app/views/translation_hints/destroy.js.erb
//This will delete the line just deleted erb syntax is #{dom_id(user)}
var flash_selector = "div#flash";
<% if not @release_status.nil? %>
  $('#translation_hint_<%=@release_status.id %>').remove();
<%end%>
$(flash_selector).html("<%=j display_flashes%>");
timeoutID = window.setTimeout(clearFlash,20000);
function clearFlash(){
  $(flash_selector).empty();
}

app/views/translation_hints/edit.html.erb
<%=theading("edit", :model=>'translation_hint', :count=>1) %>
<%= render 'form' %>
<%if has_role? :translation_hints_create%>
<%=link_new( new_translation_hint_path, :translation_hint)  %> |
<%end%> 
<%=link_back(translation_hints_path) %>

app/views/translation_hints/index.html.erb
<%require 'will_paginate/array' %>
<%=theading("listing", :model=>'translation_hint', :count=>11) %>
<%if TranslationHint.respond_to?( :searchable_attr ) && TranslationHint.searchable_attr.any? then %>
<div id = 'data-empty' style = 'display:none'><%= @translation_hints.empty?.to_s %></div>
<button id="showHideCriteria" type='button'>x</button>
<div id='criteria' class="criteria" >
  <!-- Use form_tag here because we are not going to work with a new AR model. form_tag doesn't work with formtastic either -->
  <!-- See controller#index doc for how to use this stuff below. 
    YOU NEED TO ADD METHODS TO MODEL BEFORE THIS PAGE WILL WORK -->
  <%= form_tag translation_hints_path, :method => 'get', :class=>'formtastic' do %>
    <!--    These next 2 hidden fields needed for sorting from column headers -->
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <fieldset class="inputs">
      <ol>
     
      <%if TranslationHint.searchable_attr.include?("dot_key_code") %>  
      <li class="string optional" id="translation_hint_dot_key_code_input"><label for="criterion-dot_key_code" class="criteria-label" >
        <%= tlabel("dot_key_code", "translation_hint") %> </label>
           <%=select_tag(  :operator_dot_key_code, options_for_select(operators_2_options(Translation.search_dot_key_code_operators), params[:operator_dot_key_code]),{:include_blank=> true,:class=>'criteria-operators-select', :readonly=>true} ) %> 
           
           <%=text_field_tag( :criterion_dot_key_code, params[:criterion_dot_key_code])%>
      </li> 
      <%end #if  attribute in searchable %> 
       
       <%if TranslationHint.searchable_attr.include?("heading") %>  
      <li class="string optional" id="translation_hint_heading_input"><label for="criterion-heading" class="criteria-label" >
        <%= tlabel("heading", "translation_hint") %> </label>
           <%=select_tag(  :operator_heading, options_for_select(operators_2_options(equal_operator), params[:operator_heading]),{:include_blank=> true,:class=>'criteria-operators-select', :readonly=>true} ) %> 
           <!-- The date pikcer here cannot reset itself: once a user chooses a date then the only way of having it not considered it to set it to, say 2000-01-01 and criterion to after
             Not pretty but whoever makes datepicker doesn't want a reset function as part of it http://jsbin.com/ofare/edit#javascript,html may be a work around -->
           <%=text_field_tag( :criterion_heading, params[:criterion_heading])%>
      </li> 
      <%end %>
      
      <%if TranslationHint.searchable_attr.include?("example") %>  
      <li class="string optional" id="translation_hint_example_input"><label for="criterion-example" class="criteria-label" >
        <%= tlabel("example", "translation_hint") %> </label>
           <%=select_tag(  :operator_example, options_for_select(operators_2_options(equal_operator), params[:operator_example]),{:include_blank=> true,:class=>'criteria-operators-select', :readonly=>true} ) %> 
           <!-- The date pikcer here cannot reset itself: once a user chooses a date then the only way of having it not considered it to set it to, say 2000-01-01 and criterion to after
             Not pretty but whoever makes datepicker doesn't want a reset function as part of it http://jsbin.com/ofare/edit#javascript,html may be a work around -->
           <%=text_field_tag( :criterion_example, params[:criterion_example])%>
      </li> 
      <%end #if  attribute in searchable %> 
     
      <%if TranslationHint.searchable_attr.include?("description") %>  
      <li class="string optional" id="translation_hint_description_input"><label for="criterion-description" class="criteria-label" >
        <%= tlabel("description", "translation_hint") %> </label>
           <%=select_tag(  :operator_description, options_for_select(operators_2_options(Translation.search_translation_operators), params[:operator_description]),{:include_blank=> true,:class=>'criteria-operators-select', :readonly=>true} ) %> 
           <!-- The date pikcer here cannot reset itself: once a user chooses a date then the only way of having it not considered it to set it to, say 2000-01-01 and criterion to after
             Not pretty but whoever makes datepicker doesn't want a reset function as part of it http://jsbin.com/ofare/edit#javascript,html may be a work around -->
           <%=text_field_tag( :criterion_description, params[:criterion_description])%>
      </li> 
      <%end #if  attribute in searchable %> 
     
     </ol> 
   </fieldset>
      
      <%= submit_tag "Search", :name => nil %>
  <%end  #end form_tag do%>

</div>
<%end # if searchable_attr %>

<% if @translation_hints.count == 0 then %>
  
<%  else %>
    <%= twill_paginate %>

    <% if TranslationHint.respond_to? :sortable_attr
      sortable_cols = TranslationHint.sortable_attr
    else
      sortable_cols = []
    end %>

  <table class="data" style="table-layout: fixed; width:95%;">
    <tr class="dataheader">
      <th class ="dataheader"><%=sortable("dot_key_code","translation_hint", sortable_cols.include?("dot_key_code"))%></th>
      <th class ="dataheader"><%=sortable("heading","translation_hint", sortable_cols.include?("heading"))%></th> 
      <th class ="dataheader"><%=sortable("example","translation_hint", sortable_cols.include?("example"))%></th>     
      <th class ="dataheader"><%=sortable("description","translation_hint", sortable_cols.include?("description"))%></th> 
      <%if has_role? :translation_hints_write%>  
        <%= link_header 1 %>
      <%end%>  
      <%if has_role? :translation_hints_destroy%>  
        <%= link_header 1 %>
      <%end%>
    </tr>
  
    
  <% cell_class = "data" %>
  <% link_cell_class="link"%>  
  <% @translation_hints.each do |translation_hint| %>
  
    <tr class = "<%= cycle('dataeven', 'dataodd') %>" id = '<%= dom_id(translation_hint)%>'>
            <td class="<%= cell_class %>" style="word-wrap: break-word;width:8%;"><%= translation_hint.dot_key_code %></td>
            <td class="<%= cell_class %>" style="word-wrap: break-word;width:8%;"><%= translation_hint.heading %></td>
  
            <td class="<%= cell_class %>"style="word-wrap: break-word;width:28%;"><%= translation_hint.example %></td>
  
            <td class="<%= cell_class %>"style="word-wrap: break-word;width:28%;"><%= translation_hint.description %></td>
            <%if has_role? :translation_hints_write%>
               <%= link_edit( edit_translation_hint_path(translation_hint), :translation_hints, {:style=> "width:8%;"}  ) %>
            <%end%>
            <%if has_role? :translation_hints_destroy%>
              <%= link_destroy( translation_hint, :translation_hints ) %>
            <%end%>
    </tr>
  <% end #do data %>
  </table>
  <%= twill_paginate %>

<br />
<%end # if else count %>
<%if has_role? :translation_hints_create%>
<%=link_new( new_translation_hint_path, :translation_hint)  %> 
<%end%>

app/views/translation_hints/new.html.erb
<%=theading("new", :model=>'translation_hint', :count=>1) %>
<%= render 'form' %>
<%if has_role? :translation_hints_create%>
<%=link_new( new_translation_hint_path, :translation_hint)  %> |
<%end%> 
<%=link_back(translation_hints_path )%>

app/views/translation_hints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= tlabel('heading', '') %>:</b>
  <%= @translation_hint.heading %>
</p>

<p>
  <b><%= tlabel('example', '') %>:</b>
  <%= @translation_hint.example %>
</p>

<p>
  <b><%= tlabel('description', '') %>:</b>
  <%= @translation_hint.description %>
</p>

<%if has_role? :translatiion_hints_create%>
<%=link_edit('edit', edit_translation_hint_path(@translation_hint)) %> |
<%end%>
<%= link_back(translation_hints_path) %>