config/routes.rb
Translate::Application.routes.draw do

  

  
  
  scope "/:locale" do
   resources :profiles
   resources :translation_hints
   resources :translations_uploads
   resources :contacts
   resources :delayed_jobs
   root :to => 'help#application'
   get 'help/application', :to => 'help#application', :as => 'application_help'
   get 'help/translator', :to => 'help#translator', :as => 'translator_help'
   get 'help/translator_objects', :to => 'help#translator_objects', :as => 'translator_objects_help'
   get 'help/translation_process', :to => 'help#translation_process', :as => 'translation_process_help'
   get 'help/interpolations', :to => 'help#interpolations', :as => 'translation_interpolations_help'
   get 'help/developer', :to => 'help#developer', :as =>  'developer_help'
   get 'help/administrator', :to => 'help#administrator', :as => 'administrator_help'
   get 'help/role_of_english', :to => 'help#role_of_english', :as => 'role_of_english_help'
   get 'help/redis_databases', :to => 'help#redis_databases', :as => 'redis_databases_help' 
   get 'help/redis_instances', :to => 'help#redis_instances', :as => 'redis_instances_help'
   get 'help/getting_started', :to => 'help#getting_started', :as => 'getting_started'
   get 'help/admin_getting_started', :to => 'help#admin_getting_started', :as => 'admin_getting_started'
   get 'help/admin_users', :to => 'help#user_admin', :as => 'user_admin'
   get 'help/admin_applications_versions_languages', :to => 'help#admin_applications_versions_languages', :as => 'admin_applications_versions_languages'
   get 'help/todo', :to => 'help#todo', :as => 'todo'
   get 'help/contents', :to=> 'help#contents', :as => 'contents'
   get 'help/admin_publishing', :to=> 'help#publishing', :as => 'publishing'
   get 'help/translator_publishing', :to=> "help#translatorpublishing", :as => "translator_publishing_help"
   get 'help/administrator_publishing', :to => "help#administrator_publishing", :as => 'administrator_publishing_help'
   get 'help/admin_uploading', :to=> 'help#uploading', :as => 'uploading'
   get 'help/translator_ui', :to => 'help#translator_ui', :as => 'translator_ui'
   get 'help/developers_english', :to => 'help#developers_english', :as => 'developers_english'
   get 'help/redis_installation', :to => 'help#redis_installation', :as => 'redis_installation'
   get 'help/deep_copy', :to => 'help#deep_copy', :as => 'help_deepcopy'
   get 'help/deep_delete', :to => 'help#deep_delete', :as => 'help_deepdelete'
   get 'help/background_processes', :to => 'help#background_processes', :as => 'background_processes'
   get 'help/prerequisites', :to => 'help#prerequisites', :as => 'prerequisites'
   get 'help/workflow', :to => 'help#admin_workflow', :as => 'admin_workflow'
   get 'help/version_15', :to => "help#version_15", :as => "version_15"
   
   
=begin
   scope "/auth_user/:user_id" do
      resources :permissions
      get '/permissions_select' => 'permissions#select',      :as => :permissions_select, via: :all
      get '/set_permission/:id' => 'permissions#set_current', :as => :set_permission, via: :all
   end
   
   get '/auth_user/set_permission_by_ajax' => 'permissions#set_current_by_ajax', :as => :set_permission_by_ajax, via: :all
=end   
    
=begin
   devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}, 
     controllers: {confirmations: "users/confirmations", passwords: "users/passwords", registrations: "users/registrations", 
         sessions: "users/sessions", 
         unlocks: "users/unlocks", :invitations => 'users/invitations'}
=end
   devise_for :users, :controllers => { :invitations => 'invitations', sessions: "users/sessions" }
     match '/users/:id', :to => 'users#destroy', :as => :destroy_user, :via => :delete
     get "users/:id/edit_password",   :to => "users#edit",   :as => :edit_password
     get "users/:id/user_own_data_update", :to => "users#user_own_data_update", :as => :user_own_data_update  
     get "users/:id/user_own_data_edit", :to => "users#user_own_data_edit", :as => :user_own_data_edit
     patch "users/:id/update_password", :to => "users#update", :as => :update_password  
     patch "users/:id/unlock_user",     :to => "users#unlock_user", :as => :unlock_user
     get "users/new", :to => "users#new", :as => "new_user" 
     get "users/:id/edit", :to=> "users#edit", :as => :user_edit 
     post "users/create", :to=> "users#create", :as => :user_create
     patch "users/:id/update", :to=> "users#update", :as => :user_update
     post "users/add_invitation", :to => "users#invite_user", :as => :invite_user
     get "users/send_timezone_offset", :to => "users#timezone_offset", :as => "send_timezone_offset" 
    get "delayed_job/start", :to => "delayed_jobs#start", :as => "start_delayed_jobs_queue"
    
   resources :languages
   resources :users, :only => [:index]
   resources :whiteboard_types
   resources :whiteboards

   resources :translation_languages

    
   resources :calmapps
   resources :calmapp_versions
   post "calmapp_versions/deep_copy"=> "calmapp_versions#deep_copy", :as=>"version_deep_copy"
   get "calmapp_versions/deep_copy_params/:id"=> "calmapp_versions#deep_copy_params", :as=>"version_deep_copy_params"
   get "calmapp_versions_translation_languages/deep_copy"=> "calmapp_versions_translation_languages#deep_copy", :as=>"version_translation_language_deep_copy"
   delete "calmapp_versions_translation_languages/deep_destroy/:id" => "calmapp_versions_translation_languages#deepdestroy", :as => "versions_language_deepdestroy"
   delete "calmapp_versions/deep_destroy/:id" => "calmapp_versions#deepdestroy", :as => "version_deepdestroy"
   
   
   resources :release_statuses
   resources :redis_databases, :only=>[:index, :destroy, :edit]
   resources :redis_instances
   get 'unused_redis_database_indexes' => 'redis_instances#unused_redis_database_indexes', :as => 'redis_databases_getunused', via: :all
   get 'next_unused_redis_database_index'=> 'redis_instances#next_redis_database_index'  , :as => 'redis_databases_getnextindex', :via=> :all
   
   resources :calmapp_versions_translation_languages
   resources :translations #, :except=>:show#, :only=> [:new, :index]
   get "translations/dev_new" => "translations#dev_new", :as => "dev_new_translation", via: :all
   get "translations/dev_create" => "translations#dev_create", :as => "dev_create_translation", via: :all
   resources :translation_parameters, :only=> [ :new, :index]
   resources :special_partial_dot_keys
   

   get "redis_databases/redis_to_yaml/:id" => "redis_databases#redis_to_yaml", :as => "redis_to_yaml", via: :all
   get "calmapp_version/version_alterredisdb/:id" => "calmapp_versions#redisdbalter", :as => "version_alterredisdb"#, via: :all
   post "calmapp_version/version_publish/:id" => "redis_databases#versionpublish", :as =>"redis_databases_versionpublish" #, :via => :all
   post "calmapp_versions_translation_language/publish/:id" => "calmapp_versions_translation_languages#languagepublish", :as =>"calmapp_versions_translation_languages_languagepublish", :defaults => { :format => 'js' }
   post "calmapp_versions_translation_language/translatorproductionpublish/:id" => "calmapp_versions_translation_languages#translatorproductionpublish", :as =>"calmapp_versions_translation_languages_translatorproductionpublish", :defaults => { :format => 'js' }
   get "calmapp_versions_translation_language/translatorpublish/:id" => "calmapp_versions_translation_languages#translatorpublish", :as => "translator_publish", :defaults => { :format => 'js' }
   get "users/:id/request_translators_dbs", :to=> "users#translatorpublishing", :as => "translator_publishing"
   
   resources :translation_editor_params
   resources :special_partial_dot_keys
   resources :dot_key_code_translation_editors, :only=> [:index, :edit, :show] 
   

   get '/about',   :to => 'static_pages#about'
  end

end

app/views/translations_uploads deprecated/index.html.erb
<script type="text/javascript">
//This script  handles showing and hiding selection criteria
  var criteriaDiv ="#criteria";
  var criteriaButton = "#showHideCriteria";
  $().ready(function(){
    //Initialise the criteria to be hidden on first display
    $(criteriaDiv).hide(); 
    $(criteriaButton).html(criteriaHiddenText);
    
    if( <%= @translations_uploads.count==0 %>){
      toggleCriteria();
    }
    
    $(criteriaButton).click(function(){
      toggleCriteria();
    }); //end click
  });//end ready
  var   criteriaHiddenText = "<%=t($FA +'show_something', :something=>t($SC))%>";
  var   criteriaVisibleText = "<%=t($FA +'hide_something', :something=>t($SC))%>";
  function toggleCriteria(){
    if($(criteriaDiv).is(':visible')){ 
        $(criteriaButton).html(criteriaHiddenText);
    }else{
        $(criteriaButton).html(criteriaVisibleText);
    }
    // toggle has to be after setting button text otherwise is(':visible') will not work properly
    $(criteriaDiv).slideToggle('slow');  
  }
  
</script>
<%=theading("listing", :model=>'translations_upload', :count=>11) %>
<%if TranslationsUpload.respond_to?( :searchable_attr ) and TranslationsUpload.searchable_attr.any? then %>
<button id="showHideCriteria" type='button'>x</button>
<div id='criteria' class="criteria" >
  <!-- Use form_tag here because we are not going to work with a new AR model. form_tag doesn't work with formtastic either -->
  <!-- See controller#index doc for how to use this stuff below. 
    YOU NEED TO ADD METHODS TO MODEL BEFORE THIS PAGE WILL WORK -->
  <%= form_tag translations_uploads_path, :method => 'get', :class=>'formtastic' do %>
    <!--    These next 2 hidden fields needed for sorting from column headers -->
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <fieldset class="inputs">
      <ol>
     
      <%if TranslationsUpload.searchable_attr.include?("translation_language_id") %>  
      <li class="string optional" id="translations_upload_translation_language_id_input"><label for="criteriontranslation_language_id" class="criteria-label" >
        <%= tlabel("translation_language_id", "translations_upload") %> </label>
           <%=select_tag(  :operator_translation_language_id, options_for_select(operators_2_options(equal_operator), params[:operator_translation_language_id]),{:include_blank=> true,:class=>'criteria-operators-select', :readonly=>true} ) %> 
           <!-- The date pikcer here cannot reset itself: once a user chooses a date then the only way of having it not considered it to set it to, say 2000-01-01 and criterion to after
             Not pretty but whoever makes datepicker doesn't want a reset function as part of it http://jsbin.com/ofare/edit#javascript,html may be a work around -->
           <%=text_field_tag( :criterion_translation_language_id, params[:criterion_translation_language_id])%>
      </li> 
      <%end #if  attribute in searchable %> 
     
      <%if TranslationsUpload.searchable_attr.include?("description") %>  
      <li class="string optional" id="translations_upload_description_input"><label for="criteriondescription" class="criteria-label" >
        <%= tlabel("description", "translations_upload") %> </label>
           <%=select_tag(  :operator_description, options_for_select(operators_2_options(equal_operator), params[:operator_description]),{:include_blank=> true,:class=>'criteria-operators-select', :readonly=>true} ) %> 
           <!-- The date pikcer here cannot reset itself: once a user chooses a date then the only way of having it not considered it to set it to, say 2000-01-01 and criterion to after
             Not pretty but whoever makes datepicker doesn't want a reset function as part of it http://jsbin.com/ofare/edit#javascript,html may be a work around -->
           <%=text_field_tag( :criterion_description, params[:criterion_description])%>
      </li> 
      <%end #if  attribute in searchable %> 
     
     </ol> 
   </fieldset>
      
      <%= submit_tag "Search", :name => nil %>
  <%end  #end form_tag do%>

</div>
<%end # if searchable_attr %>

<% if @translations_uploads.count == 0 then %>
  
<%  else %>
    <%= twill_paginate %>

    <% if TranslationsUpload.respond_to? :sortable_attr
      sortable_cols = TranslationsUpload.sortable_attr
    else
      sortable_cols = []
    end %>

  <table class="data">
    <tr class="dataheader">
      <td class = "dataheader">Version/language</td>
      <!--th class ="dataheader">< %=sortable("translation_language_id","translations_upload", sortable_cols.include?("translation_language_id"))%></th --> 
      <!--th class ="dataheader">< %=sortable("calmapp_version_id","translations_upload", sortable_cols.include?("calmapp_version_id"))%></th -->
    
      <th class ="dataheader"><%=sortable("description","translations_upload", sortable_cols.include?("description"))%></th> 
  
        <%= link_header 2 %>
      
    </tr>
  
    
  <% cell_class = "data" %>
  <% link_cell_class="link"%>  
  <% @translations_uploads.each do |translations_upload| %>
  
    <tr class = "<%= cycle('dataeven', 'dataodd') %>" >
            <td class="<%= cell_class %>"><!--%= translations_upload.calmapp_versions_translation_language.name % --></td>
            <!--td class="< %= cell_class %>">< %= translations_upload.translation_language.name %></td-->
             <!--td class="<%= cell_class %>">< %= translations_upload.calmapp_version.name%></td -->
            <td class="<%= cell_class %>"><%= translations_upload.description %></td>
            <!--td class="< %= cell_class %>"> < %=translations_upload.yaml_upload_file_name% ></td -->
            <td class="<%= cell_class %>"> <%=translations_upload.yaml_upload%></td>
          <%= link_edit( edit_translations_upload_path(translations_upload), :translations_uploads  ) %>
      <%= link_destroy( translations_upload, :translations_uploads ) %>
      
    </tr>
  <% end #do data %>
  </table>
  <%= twill_paginate %>

<br />
<%end # if else count %>
<%=link_new( new_translations_upload_path, :translations_upload)  %>