config/routes.rb
Translate::Application.routes.draw do

  

  
  
  scope "/:locale" do
   resources :profiles
   resources :translation_hints
   resources :translations_uploads
   resources :contacts
   resources :delayed_jobs
   root :to => 'help#application'
   get 'help/application', :to => 'help#application', :as => 'application_help'
   get 'help/translator', :to => 'help#translator', :as => 'translator_help'
   get 'help/translator_objects', :to => 'help#translator_objects', :as => 'translator_objects_help'
   get 'help/translation_process', :to => 'help#translation_process', :as => 'translation_process_help'
   get 'help/interpolations', :to => 'help#interpolations', :as => 'translation_interpolations_help'
   get 'help/developer', :to => 'help#developer', :as =>  'developer_help'
   get 'help/administrator', :to => 'help#administrator', :as => 'administrator_help'
   get 'help/role_of_english', :to => 'help#role_of_english', :as => 'role_of_english_help'
   get 'help/redis_databases', :to => 'help#redis_databases', :as => 'redis_databases_help' 
   get 'help/redis_instances', :to => 'help#redis_instances', :as => 'redis_instances_help'
   get 'help/getting_started', :to => 'help#getting_started', :as => 'getting_started'
   get 'help/admin_getting_started', :to => 'help#admin_getting_started', :as => 'admin_getting_started'
   get 'help/admin_users', :to => 'help#user_admin', :as => 'user_admin'
   get 'help/admin_applications_versions_languages', :to => 'help#admin_applications_versions_languages', :as => 'admin_applications_versions_languages'
   get 'help/todo', :to => 'help#todo', :as => 'todo'
   get 'help/contents', :to=> 'help#contents', :as => 'contents'
   get 'help/admin_publishing', :to=> 'help#publishing', :as => 'publishing'
   get 'help/translator_publishing', :to=> "help#translatorpublishing", :as => "translator_publishing_help"
   get 'help/administrator_publishing', :to => "help#administrator_publishing", :as => 'administrator_publishing_help'
   get 'help/admin_uploading', :to=> 'help#uploading', :as => 'uploading'
   get 'help/translator_ui', :to => 'help#translator_ui', :as => 'translator_ui'
   get 'help/developers_english', :to => 'help#developers_english', :as => 'developers_english'
   get 'help/redis_installation', :to => 'help#redis_installation', :as => 'redis_installation'
   get 'help/deep_copy', :to => 'help#deep_copy', :as => 'help_deepcopy'
   get 'help/deep_delete', :to => 'help#deep_delete', :as => 'help_deepdelete'
   get 'help/background_processes', :to => 'help#background_processes', :as => 'background_processes'
   get 'help/prerequisites', :to => 'help#prerequisites', :as => 'prerequisites'
   get 'help/workflow', :to => 'help#admin_workflow', :as => 'admin_workflow'
   get 'help/version_15', :to => "help#version_15", :as => "version_15"
   
   
=begin
   scope "/auth_user/:user_id" do
      resources :permissions
      get '/permissions_select' => 'permissions#select',      :as => :permissions_select, via: :all
      get '/set_permission/:id' => 'permissions#set_current', :as => :set_permission, via: :all
   end
   
   get '/auth_user/set_permission_by_ajax' => 'permissions#set_current_by_ajax', :as => :set_permission_by_ajax, via: :all
=end   
    
=begin
   devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}, 
     controllers: {confirmations: "users/confirmations", passwords: "users/passwords", registrations: "users/registrations", 
         sessions: "users/sessions", 
         unlocks: "users/unlocks", :invitations => 'users/invitations'}
=end
   devise_for :users, :controllers => { :invitations => 'invitations', sessions: "users/sessions" }
     match '/users/:id', :to => 'users#destroy', :as => :destroy_user, :via => :delete
     get "users/:id/edit_password",   :to => "users#edit",   :as => :edit_password
     get "users/:id/user_own_data_update", :to => "users#user_own_data_update", :as => :user_own_data_update  
     get "users/:id/user_own_data_edit", :to => "users#user_own_data_edit", :as => :user_own_data_edit
     patch "users/:id/update_password", :to => "users#update", :as => :update_password  
     patch "users/:id/unlock_user",     :to => "users#unlock_user", :as => :unlock_user
     get "users/new", :to => "users#new", :as => "new_user" 
     get "users/:id/edit", :to=> "users#edit", :as => :user_edit 
     post "users/create", :to=> "users#create", :as => :user_create
     patch "users/:id/update", :to=> "users#update", :as => :user_update
     post "users/add_invitation", :to => "users#invite_user", :as => :invite_user
     get "users/send_timezone_offset", :to => "users#timezone_offset", :as => "send_timezone_offset" 
    get "delayed_job/start", :to => "delayed_jobs#start", :as => "start_delayed_jobs_queue"
    
   resources :languages
   resources :users, :only => [:index]
   resources :whiteboard_types
   resources :whiteboards

   resources :translation_languages

    
   resources :calmapps
   resources :calmapp_versions
   post "calmapp_versions/deep_copy"=> "calmapp_versions#deep_copy", :as=>"version_deep_copy"
   get "calmapp_versions/deep_copy_params/:id"=> "calmapp_versions#deep_copy_params", :as=>"version_deep_copy_params"
   get "calmapp_versions_translation_languages/deep_copy"=> "calmapp_versions_translation_languages#deep_copy", :as=>"version_translation_language_deep_copy"
   delete "calmapp_versions_translation_languages/deep_destroy/:id" => "calmapp_versions_translation_languages#deepdestroy", :as => "versions_language_deepdestroy"
   delete "calmapp_versions/deep_destroy/:id" => "calmapp_versions#deepdestroy", :as => "version_deepdestroy"
   
   
   resources :release_statuses
   resources :redis_databases, :only=>[:index, :destroy, :edit]
   resources :redis_instances
   get 'unused_redis_database_indexes' => 'redis_instances#unused_redis_database_indexes', :as => 'redis_databases_getunused', via: :all
   get 'next_unused_redis_database_index'=> 'redis_instances#next_redis_database_index'  , :as => 'redis_databases_getnextindex', :via=> :all
   
   resources :calmapp_versions_translation_languages
   resources :translations #, :except=>:show#, :only=> [:new, :index]
   get "translations/dev_new" => "translations#dev_new", :as => "dev_new_translation", via: :all
   get "translations/dev_create" => "translations#dev_create", :as => "dev_create_translation", via: :all
   resources :translation_parameters, :only=> [ :new, :index]
   resources :special_partial_dot_keys
   

   get "redis_databases/redis_to_yaml/:id" => "redis_databases#redis_to_yaml", :as => "redis_to_yaml", via: :all
   get "calmapp_version/version_alterredisdb/:id" => "calmapp_versions#redisdbalter", :as => "version_alterredisdb"#, via: :all
   post "calmapp_version/version_publish/:id" => "redis_databases#versionpublish", :as =>"redis_databases_versionpublish" #, :via => :all
   post "calmapp_versions_translation_language/publish/:id" => "calmapp_versions_translation_languages#languagepublish", :as =>"calmapp_versions_translation_languages_languagepublish", :defaults => { :format => 'js' }
   post "calmapp_versions_translation_language/translatorproductionpublish/:id" => "calmapp_versions_translation_languages#translatorproductionpublish", :as =>"calmapp_versions_translation_languages_translatorproductionpublish", :defaults => { :format => 'js' }
   get "calmapp_versions_translation_language/translatorpublish/:id" => "calmapp_versions_translation_languages#translatorpublish", :as => "translator_publish", :defaults => { :format => 'js' }
   get "users/:id/request_translators_dbs", :to=> "users#translatorpublishing", :as => "translator_publishing"
   
   resources :translation_editor_params
   resources :special_partial_dot_keys
   resources :dot_key_code_translation_editors, :only=> [:index, :edit, :show] 
   

   get '/about',   :to => 'static_pages#about'
  end

end

app/controllers/release_statuses_controller.rb
class ReleaseStatusesController < ApplicationController
  require 'translations_helper'
  include TranslationsHelper
  # GET /release_statuses
  # GET /release_statuses.xml
  before_action :authenticate_user!
  before_action :set_release_status, only: [ :edit, :update, :destroy, :show]
  filter_access_to :all
  @@model = "release_status"
  
  def index
    @release_statuses = ReleaseStatus.paginate(:page => params[:page], :per_page=>15)  #ReleaseStatus.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @release_statuses }
    end
  end

  # GET /release_statuses/1
  # GET /release_statuses/1.xml
  def show
    #@vrelease_status = ReleaseStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @release_status }
    end
  end

  # GET /release_statuses/new
  # GET /release_statuses/new.xml
  def new
    @release_status = ReleaseStatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @release_status }
    end
  end

  # GET /release_statuses/1/edit
  def edit
    #@release_status = ReleaseStatus.find(params[:id])
  end

  # POST /release_statuses
  # POST /release_statuses.xml
  def create
    @release_status = ReleaseStatus.new(release_status_params)

    respond_to do |format|
      if @release_status.save
        tflash('create', :success, {:model=>@@model, :count=>1})
        format.html { redirect_to( release_statuses_path)} #(@release_status #, :notice => 'version status was successfully created.') }
        format.xml  { render :xml => @release_status, :status => :created, :location => @release_status }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @release_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /release_statuses/1
  # PUT /release_statuses/1.xml
  def update
    respond_to do |format|
      if @release_status.update_attributes(release_status_params)
        tflash('update', :success, {:model=>@@model, :count=>1})
        format.html { redirect_to( release_statuses_path)} #(@release_status, :notice => 'version status was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @release_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /release_statuses/1
  # DELETE /release_statuses/1.xml
  def destroy
    begin
    @release_status.destroy
    tflash('delete', :success, {:model=>@@model})
    respond_to do |format|
      format.html { redirect_to(release_statuses_path) }
      format.js {}
    end
    rescue StandardError => e
      @release_status = nil
      flash[:error] = e.message
      respond_to do |format|
        format.js
      end
    end #rescue  
  end
  
   private
    # Use callbacks to share common setup or constraints between actions.
    def set_release_status
      @release_status = ReleaseStatus.find(params[:id])
    end

    def release_status_params
        params.require(:release_status).permit(:status)
    end
    
end

app/views/release_statuses/_form.html.erb
<%= semantic_form_for(@release_status) do |f| %>
  
  
	<%= f.inputs do %>
				   <%= f.input :status  %>   
		
	<% end %>	
	<%= f.actions do %>
      <%= f.action(:submit)  %>    
  <% end %>
	
	<% end %>

app/views/release_statuses/destroy.js.erb
//This will delete the line just deleted erb syntax is #{dom_id(user)}
var flash_selector = "div#flash";
<% if not @release_status.nil? %>
  $('#release_status_<%=@release_status.id %>').remove();
<%end%>
$(flash_selector).html("<%=j display_flashes%>");
timeoutID = window.setTimeout(clearFlash,20000);
function clearFlash(){
  $(flash_selector).empty();
}

app/views/release_statuses/edit.html.erb
<%=theading("edit", :model=>"release_status", :count=>1) %>
<%= render 'form' %>
<%if has_role? :release_statuses_create%>
<%= tlink_to('new_model' , new_release_status_path,:model=>  'release_status', :count=>1) %> |
<%end%>
<%= tlink_to("back", release_statuses_path) %>

app/views/release_statuses/index.html.erb
<%=theading("listing", :model=>"release_status", :count=>10 )%>
<% if ReleaseStatus.count==0 then %>
  <%=tflash( "no_records_found", :warning)%><br/>
<%  else %>
<%= twill_paginate %>
<table class="data">
  <tr class="dataheader">

    <th class ="dataheader"><%=t($ARA+'release_status.status') %></th>
    <%if has_role? :release_statuses_write%>
    <th class="linkheader"></th>
    <%end%>
    <%if has_role? :release_statuses_destroy%>
    <th class="linkheader"></th>
    <%end%>
  </tr>

  
<% cell_class = "data" %>
<% link_cell_class="link"%>  
<% @release_statuses.each do |release_status| %>

  <tr class = "<%= cycle('dataeven', 'dataodd') %>" id = '<%= dom_id(release_status)%>'>
      
      <td class="<%= cell_class %>"><%= release_status.status %></td>

    <%if has_role? :release_statuses_write%>
    <%=link_edit(edit_release_status_path(release_status), "release_status")%>
    <%end%>
    <!--td class="<%= link_cell_class %>"><%= link_to  t('actions.edit'), edit_release_status_path(release_status) %></td -->
    <!--td class="<%= link_cell_class %>"><%= link_to t('actions.destroy'),  release_status , :confirm => t('messages.delete.are_you_sure', :model => t($ARM + "release_status", :count=>1)), :method => :delete %></td -->
    <%if has_role? :release_statuses_destroy%>
      <%=link_destroy(release_status, "release_status") %>
    <%end%>
  </tr>
<% end %>
</table>
<%= twill_paginate %>

<br />
<% end %>
<%if has_role? :release_statuses_create%>
  <%= tlink_to('new_model', new_release_status_path, :model=> 'release_status', :count=>1) %>
<%end%>

app/views/release_statuses/new.html.erb
<%= theading('new', :model=>'release_status', :count=>1)%>
<%= render 'form' %>
<%if has_role? :release_statuses_create%>
<%= tlink_to('new_model', new_release_status_path, :model=> 'release_status', :count=>1) %> |
<%end%>
<%= tlink_to "back", release_statuses_path %>

app/views/release_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @release_status.status %>
</p>

<%if has_role? :release_statuses_create%>
<%= link_to 'Edit', edit_release_status_path(@release_status) %> |
<%end%>
<%= link_to t("formtastic.actions.back"), release_statuses_path %>